/*Summirizing the ETL performed into a audit table*/
INSERT INTO AUDIT_TABLE
(
  AUDIT_DATE,
  MEMBERS_EXTRACTED,
  MEMBERS_DROPPED,
  MEMBERS_VALID,
  FLIGHTS_EXTRACTED,
  FLIGHTS_DROPPED,
  FLIGHTS_VALID
)VALUES
(
  SYSDATE,
  (SELECT TOTAL_EXTRACTED FROM AGEMEMBERAUDIT WHERE CHECKED='N'),
  (SELECT DROPPED FROM AGEMEMBERAUDIT WHERE CHECKED='N'),
  (SELECT VALID FROM AGEMEMBERAUDIT WHERE CHECKED='N'),
  (SELECT TOTAL_EXTRACTED FROM DURATIONFLIGHTSAUDIT WHERE CHECKED='N'),
  ((SELECT DROPPED FROM DURATIONFLIGHTSAUDIT WHERE CHECKED='N') +
  (SELECT DROPPED FROM PILOTINFOFLIGHTSAUDIT WHERE CHECKED='N')),
  (SELECT VALID FROM PILOTINFOFLIGHTSAUDIT WHERE CHECKED='N')
);

UPDATE AGEMEMBERAUDIT           SET CHECKED = 'Y';
UPDATE DURATIONFLIGHTSAUDIT     SET CHECKED = 'Y';
UPDATE PILOTINFOFLIGHTSAUDIT    SET CHECKED = 'Y';

--TRUNCATE TABLES
TRUNCATE TABLE VALIDPILOTINFOTAFLIGHTS;
TRUNCATE TABLE PILOT1NULLTAFLIGHTS;
TRUNCATE TABLE validDurationTaFlights;
TRUNCATE TABLE LOAD_MEMBER_PROFILE;
TRUNCATE TABLE AGETAMEMBER;
TRUNCATE TABLE STATUSTAMEMBER;
TRUNCATE TABLE VALIDAGETAMEMBER;
TRUNCATE TABLE LEFTJOINEDTAMEMBER;

TRUNCATE TABLE changedTaRegion;
TRUNCATE TABLE changedTaClub;
TRUNCATE TABLE CHANGEDTAMEMBER;
TRUNCATE TABLE changedTaFlightsVejle;
TRUNCATE TABLE changedTaFlightsSG70;
TRUNCATE TABLE changedExtPlanes;
TRUNCATE TABLE changedExtClass;
