/*
copying all the member from CHANGEDTAMEMBER into
AGETAMEMBER with transformed dateofborn into age
*/
TRUNCATE TABLE ERRORAGETAMEMBER;

INSERT
INTO AGETAMEMBER
  (
    MEMBERNO ,
    INITIALS ,
    NAME ,
    ADDRESS ,
    ZIPCODE ,
    AGE ,
    DATEJOINED ,
    DATELEFT ,
    OWNSPLANEREG ,
    STATUSSTUDENT ,
    STATUSPILOT ,
    STATUSASCAT ,
    STATUSFULLCAT ,
    SEX ,
    CLUB ,
    OPERATION
  )
SELECT MEMBERNO ,
  INITIALS ,
  NAME ,
  ADDRESS ,
  ZIPCODE ,
  CASE
    WHEN extract (YEAR FROM(sysdate - dateborn) YEAR TO MONTH) < 0
    THEN 0
    ELSE extract (YEAR FROM(sysdate - dateborn) YEAR TO MONTH)
  END ,
  DATEJOINED ,
  DATELEFT ,
  OWNSPLANEREG ,
  STATUSSTUDENT ,
  STATUSPILOT ,
  STATUSASCAT ,
  STATUSFULLCAT ,
  SEX ,
  CLUB ,
  OPERATION
FROM CHANGEDTAMEMBER;
/*
Select all the members from AGETAMEMBER into VALIDAGETAMEMBER whose
age is between 18 and 100
*/
INSERT
INTO VALIDAGETAMEMBER
  (
    MEMBERNO ,
    INITIALS ,
    NAME ,
    ADDRESS ,
    ZIPCODE ,
    AGE ,
    DATEJOINED ,
    DATELEFT ,
    OWNSPLANEREG ,
    STATUSSTUDENT ,
    STATUSPILOT ,
    STATUSASCAT ,
    STATUSFULLCAT ,
    SEX ,
    CLUB ,
    OPERATION
  )
SELECT MEMBERNO ,
  INITIALS ,
  NAME ,
  ADDRESS ,
  ZIPCODE ,
  AGE ,
  DATEJOINED ,
  DATELEFT ,
  OWNSPLANEREG ,
  STATUSSTUDENT ,
  STATUSPILOT ,
  STATUSASCAT ,
  STATUSFULLCAT ,
  SEX ,
  CLUB ,
  OPERATION
FROM AGETAMEMBER
WHERE age >= 18
AND age   <= 100 ;
/*
Select all the members from AGETAMEMBER whose age
is less than 18 or bigger than 100
*/
INSERT
INTO ERRORAGETAMEMBER
  (
    MEMBERNO ,
    INITIALS ,
    NAME ,
    ADDRESS ,
    ZIPCODE ,
    AGE ,
    DATEJOINED ,
    DATELEFT ,
    OWNSPLANEREG ,
    STATUSSTUDENT ,
    STATUSPILOT ,
    STATUSASCAT ,
    STATUSFULLCAT ,
    SEX ,
    CLUB ,
    OPERATION
  )
SELECT MEMBERNO ,
  INITIALS ,
  NAME ,
  ADDRESS ,
  ZIPCODE ,
  AGE ,
  DATEJOINED ,
  DATELEFT ,
  OWNSPLANEREG ,
  STATUSSTUDENT ,
  STATUSPILOT ,
  STATUSASCAT ,
  STATUSFULLCAT ,
  SEX ,
  CLUB ,
  OPERATION
FROM
  ( SELECT * FROM AGETAMEMBER
  MINUS
  SELECT * FROM VALIDAGETAMEMBER
  ) ;
/*
Completing audit table with the result from the process
*/
INSERT
INTO AGEMEMBERAUDIT
  (
    A_DATE,
    TOTAL_EXTRACTED,
    DROPPED,
    VALID,
    CHECKED
  )
  VALUES
  (
    (SELECT sysdate FROM dual
    )
    ,
    (SELECT COUNT(*) FROM AGETAMEMBER
    ),
    (SELECT COUNT(*) FROM ERRORAGETAMEMBER
    ),
    (SELECT COUNT(*) FROM VALIDAGETAMEMBER
    ),
    'N'
  );
INSERT
INTO STATUSTAMEMBER
  (
    MEMBERNO ,
    INITIALS ,
    NAME ,
    ADDRESS ,
    ZIPCODE ,
    AGE ,
    DATEJOINED ,
    DATELEFT ,
    OWNSPLANEREG ,
    STATUS ,
    SEX ,
    CLUB ,
    OPERATION
  )
SELECT MEMBERNO ,
  INITIALS ,
  NAME ,
  ADDRESS ,
  ZIPCODE ,
  AGE ,
  DATEJOINED ,
  DATELEFT ,
  OWNSPLANEREG ,
  CASE
    WHEN SUBSTR(STATUSSTUDENT
      || STATUSPILOT
      || STATUSASCAT
      || STATUSFULLCAT, 4, 1) = 'Y'
    THEN 'FULL CATEGORY INSTRUCTUR'
    WHEN SUBSTR(STATUSSTUDENT
      || STATUSPILOT
      || STATUSASCAT
      || STATUSFULLCAT, 3, 1) = 'Y'
    THEN 'ASSISTENT CATEGORY INSTRUCTUR'
    WHEN SUBSTR(STATUSSTUDENT
      || STATUSPILOT
      || STATUSASCAT
      || STATUSFULLCAT, 2, 1) = 'Y'
    THEN 'PILOT'
    ELSE 'STUDENT'
  END ,
  SEX ,
  CLUB ,
  OPERATION
FROM VALIDAGETAMEMBER;
------------------------------------------------------------------------------
INSERT
INTO LEFTJOINEDTAMEMBER
  (
    MEMBERNO ,
    INITIALS ,
    NAME ,
    ADDRESS ,
    ZIPCODE ,
    AGE ,
    DATEJOINED ,
    DATELEFT ,
    OWNSPLANEREG ,
    STATUS ,
    SEX ,
    CLUB ,
    OPERATION
  )
SELECT MEMBERNO ,
  INITIALS ,
  NAME ,
  ADDRESS ,
  ZIPCODE ,
  AGE ,
  CASE
    WHEN datejoined > dateleft
    AND dateleft   IS NOT NULL
    THEN dateleft
    ELSE datejoined
  END ,
  CASE
    WHEN dateleft < datejoined
    AND dateleft IS NOT NULL
    THEN datejoined
    ELSE dateleft
  END ,
  OWNSPLANEREG ,
  STATUS ,
  SEX ,
  CLUB ,
  OPERATION
FROM STATUSTAMEMBER;
