/*
  Flights with invalid pilot info will not be accepeted and will be thrown 
  into an error table.
  Flights with invalid pilot info is considered to be fights whose pilot
  initials are not in D_MEMBER table;
*/

/*IF THE FIRST PILOT IS NULL AND THE SECOND ONE IS NOT NULL WE CAN ASSUME 
THERE IS A MISTAKE COMMITED IN THE SOURCE. WHY WE ARE CONSIDERING THAT THE
SECOND PILOT IS ACTUALLY THE FIRST ONE;*/
INSERT INTO PILOT1NULLTAFLIGHTS
(      LAUNCHDATE,
        LAUNCHTIME,
        LANDINGDATE,
        LANDINGTIME,
        PLANEREGISTRATION,
        PILOT1INIT,
        PILOT2INIT,
        LAUNCHAEROTOW,
        LAUNCHWINCH,
        LAUNCHSELFLAUNCH,
        CABLEBREAK,
        CROSSCOUNTRYKM,
        CLUB)
        SELECT LAUNCHDATE,
        LAUNCHTIME,
        LANDINGDATE,
        LANDINGTIME,
        PLANEREGISTRATION,
        CASE
          WHEN TRIM(PILOT1INIT) IS NULL THEN PILOT2INIT
          ELSE PILOT1INIT
          END,
          CASE
          WHEN TRIM(PILOT1INIT) IS NULL THEN ''
          ELSE PILOT2INIT
          END,
        LAUNCHAEROTOW,
        LAUNCHWINCH,
        LAUNCHSELFLAUNCH,
        CABLEBREAK,
        CROSSCOUNTRYKM,
        CLUB FROM VALIDDURATIONTAFLIGHTS;


/*IF THERE ARE SOME FLIGHTS WITH PILOT INITIALS WHICH ARE NOT IN D_MEMBERPROFILE
TABLE, THEY WILL BE PLACED INTO AN ERROR TABLE.*/
INSERT INTO VALIDPILOTINFOTAFLIGHTS
(
        LAUNCHDATE,
        LAUNCHTIME,
        LANDINGDATE,
        LANDINGTIME,
        PLANEREGISTRATION,
        PILOT1INIT,
        PILOT2INIT,
        LAUNCHAEROTOW,
        LAUNCHWINCH,
        LAUNCHSELFLAUNCH,
        CABLEBREAK,
        CROSSCOUNTRYKM,
        CLUB
)SELECT LAUNCHDATE,
        LAUNCHTIME,
        LANDINGDATE,
        LANDINGTIME,
        PLANEREGISTRATION,
        PILOT1INIT,
        PILOT2INIT,
        LAUNCHAEROTOW,
        LAUNCHWINCH,
        LAUNCHSELFLAUNCH,
        CABLEBREAK,
        CROSSCOUNTRYKM,
        CLUB FROM PILOT1NULLTAFLIGHTS
        WHERE PILOT1INIT IN (
        SELECT INITIALS FROM D_MEMBERPROFILE)
        AND (PILOT2INIT IN (
        SELECT INITIALS FROM D_MEMBERPROFILE) OR
        TRIM(PILOT2INIT) IS NULL
        );

INSERT INTO VALIDPILOTINFOTAFLIGHTS
(
        LAUNCHDATE,
        LAUNCHTIME,
        LANDINGDATE,
        LANDINGTIME,
        PLANEREGISTRATION,
        PILOT1INIT,
        PILOT2INIT,
        LAUNCHAEROTOW,
        LAUNCHWINCH,
        LAUNCHSELFLAUNCH,
        CABLEBREAK,
        CROSSCOUNTRYKM,
        CLUB
)SELECT LAUNCHDATE,
        LAUNCHTIME,
        LANDINGDATE,
        LANDINGTIME,
        PLANEREGISTRATION,
        PILOT2INIT,
        '',
        LAUNCHAEROTOW,
        LAUNCHWINCH,
        LAUNCHSELFLAUNCH,
        CABLEBREAK,
        CROSSCOUNTRYKM,
        CLUB FROM PILOT1NULLTAFLIGHTS
        WHERE PILOT1INIT NOT IN (
        SELECT INITIALS FROM D_MEMBERPROFILE)
        AND (PILOT2INIT IN (
        SELECT INITIALS FROM D_MEMBERPROFILE) AND
        TRIM(PILOT2INIT) IS NOT NULL
        );


INSERT INTO VALIDPILOTINFOTAFLIGHTS
(
        LAUNCHDATE,
        LAUNCHTIME,
        LANDINGDATE,
        LANDINGTIME,
        PLANEREGISTRATION,
        PILOT1INIT,
        PILOT2INIT,
        LAUNCHAEROTOW,
        LAUNCHWINCH,
        LAUNCHSELFLAUNCH,
        CABLEBREAK,
        CROSSCOUNTRYKM,
        CLUB
)SELECT LAUNCHDATE,
        LAUNCHTIME,
        LANDINGDATE,
        LANDINGTIME,
        PLANEREGISTRATION,
        PILOT1INIT,
        '',
        LAUNCHAEROTOW,
        LAUNCHWINCH,
        LAUNCHSELFLAUNCH,
        CABLEBREAK,
        CROSSCOUNTRYKM,
        CLUB FROM PILOT1NULLTAFLIGHTS
        WHERE PILOT1INIT IN (
        SELECT INITIALS FROM D_MEMBERPROFILE)
        AND (PILOT2INIT NOT IN (
        SELECT INITIALS FROM D_MEMBERPROFILE) AND 
        TRIM(PILOT2INIT) IS NOT NULL
        );
  
  /*COMPLETING AUDIT TABLE WITH NECESSARY INFORMATION*/
    INSERT INTO PILOTINFOFLIGHTSAUDIT
    (
      A_DATE,
      TOTAL_EXTRACTED,
      DROPPED,
      VALID,
      CHECKED
    )VALUES(
      SYSDATE,
      (SELECT COUNT(*) FROM VALIDDURATIONTAFLIGHTS),
      ((SELECT COUNT(*) FROM VALIDDURATIONTAFLIGHTS)- (SELECT COUNT(*) FROM VALIDPILOTINFOTAFLIGHTS)),
      (SELECT COUNT(*) FROM VALIDPILOTINFOTAFLIGHTS),
      'N'); 